### ISSUE TITLE
Design - Homepage

### ISSUE THREAD

**Issue by LilyMihalik** [jperezlatimes/hsinsider#1]

**Comment by LilyMihalik** [comment]
Using new font - via google fonts: <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,200,300,600' rel='stylesheet' type='text/css'>

font-family: 'Source Sans Pro', sans-serif;
headline: Extra-Light 200
bylines and school: Light 300

anything we want to bold: Semi-Bold 600


![hs-insider-main-index](https://cloud.githubusercontent.com/assets/1634854/10433630/59e3447c-70c8-11e5-9fb1-ed425a6f3a3a.jpg)

**Comment by jperezlatimes** [comment]
This looks good! :+1:

**Comment by LilyMihalik** [comment]
@jperezlatimes awesome! I'm working on the port page now. and the school index page. more on that soon - took me a while to setting on this landing page. so many options. ...

**Comment by KyleFinck** [comment]
Can we add a second set of leaderboard (300x600) and cube (300x250)?
![2nd ad slots](https://cloud.githubusercontent.com/assets/11601847/10464021/8b9262e4-719c-11e5-9dda-475e7924dcac.png)
 ads in same dimensions.

**Comment by LilyMihalik** [comment]
Also, note that the sidebar, I just screenshotted - it will also be google sans source pro . @KyleFinck I think we should be able to adjust the ad map -though I do get worried about to many ads on the page - since it's for kids etc

**Comment by KyleFinck** [comment]
@LilyMihalik sounds good. I don't think 4 ads would be too much, because the page scroll is fairly long. Also, the ad map we have right now is very complicated. Talking with @jperezlatimes we can't implement many of these ad specs (such as a premium ad takeover). I think the ad map needs to be simplified. Thoughts? 

![hsi-index-admaps](https://cloud.githubusercontent.com/assets/11601847/10465053/c2ef73e4-71a1-11e5-81bf-b500b7a209f1.jpg)

**Comment by KyleFinck** [comment]
oops, sorry. it didn't upload the entire page.
